# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: G-QYT9CL3F7L
title: Ki-won 개발 일지

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Ki-won

description: Stylish Jekyll Theme
author:
  name: Seo Ki-won
  email: seokw2240@gmail.com
  github: https://github.com/kiwon7602
  bio: 수상할 정도로 용어 설명을 못하는 주니어 개발자 
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
